# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_generic" "ehci_pci" "ahci" "isci" "xhci_pci" "firewire_ohci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ad79fdf0-31ec-418f-a6ec-6980ac38b0f8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-47c3a1d4-4b39-4712-9f20-bb51bddff22e".device = "/dev/disk/by-uuid/47c3a1d4-4b39-4712-9f20-bb51bddff22e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0CCE-DECB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/storagebox" = {
    device = "https://u416901.your-storagebox.de/";
    fsType = "davfs";
    options = ["user" "noauto"]; # Add additional options as needed
  };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/cc45fb15-f63e-42d8-8de4-91bc5d26f484"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
